version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.qufrlaajxqfebtvgdnaj
      - SPRING_DATASOURCE_PASSWORD=MaiTieuBao1234!@#$
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    restart: always
